### ISSUE TITLE
Doesn't work on Proton

### ISSUE THREAD

**Issue by eris-webserv** [mindustry-antigrief/installer#2]
Atempting to use this on Proton leads to the game not finding a Java binary.
What I tried:
- Install Java using Wine (Did nothing)

**Comment by buthed010203** [comment]
Install client manually then, too much work to fix this lmao

Real question: Why are you even playing a linux game through proton? wtf

**Comment by eris-webserv** [comment]
To answer your question (I was busy. Very busy): I use Steam a lot, and on Steam there's only the Windows build. So...
Also, it seems either *you* fixed it or Steam fixed it. Either way it works with Proton now so I'm considering this completed /shrug

**Comment by buthed010203** [comment]
There's literally a linux build on windows...

**Comment by eris-webserv** [comment]
**I prefer to use Steam for my games.** Managing manual installs of most games is tedious.

EDIT: I thought I said I liked to use Steam before. I was wrong.

**Comment by buthed010203** [comment]
> **I prefer to use Steam for my games.** Managing manual installs of most games is tedious.
> 
> EDIT: I thought I said I liked to use Steam before. I was wrong.

????? Theres a linux build on steam sir. Ask foo, he uses it. Hell [steamdb shows it too](https://steamdb.info/depot/1127403/)

**Comment by eris-webserv** [comment]
?!?!?!?!??!

Last I checked it Mindustry on Steam only supported Windows! Did Steam lie to me when I reinstalled Mindustry?
